"""
Web search agent using DuckDuckGo and Ollama LLM.
Retrieves live web results and summarizes them for the user.
"""

import re
import ollama
from ddgs import DDGS

OLLAMA_MODEL = "llama3.2"

WEB_SYSTEM_PROMPT = """You are a web search assistant. Answer the user's question using ONLY the web search results provided below.
- Cite sources inline using [Source N] notation matching the result headers.
- Be concise and synthesize across sources when relevant.
- If the results do not contain enough information to answer the question, say: "The search results don't contain enough information to answer this question."
- Do not fabricate information not present in the results."""


def web_search(query, max_results=5, conversation_history=None):
    """
    Search the web using DuckDuckGo and summarize results with Ollama.

    Args:
        query: User's search query
        max_results: Number of web results to retrieve (default: 5)

    Returns:
        tuple: (answer: str, result_count: int, tokens_in: int, tokens_out: int, grounded: bool)
            - answer: Generated answer from web search, or "" if no results or error
            - result_count: Number of web results used
            - tokens_in: Input tokens used by Ollama
            - tokens_out: Output tokens generated by Ollama
            - grounded: True if proper nouns from query appear in result bodies/titles
        Raises:
            RuntimeError: If DuckDuckGo API fails (triggers LangGraph retry)
    """
    try:
        results = list(DDGS().text(query, max_results=max_results))
    except Exception as e:
        raise RuntimeError(f"DuckDuckGo search failed: {e}")

    if not results:
        print("No web search results found.")
        return "", 0, 0, 0, True  # Empty results → can't verify groundedness

    # Extract proper nouns from query (capitalized words, potential product/company names)
    query_words = re.findall(r'\b[A-Z][a-zA-Z]{2,}\b', query)
    # Filter common English question words that won't appear in sources meaningfully
    stopwords = {"What", "How", "Why", "Who", "When", "Where", "Tell", "Does", "The", "This", "That", "Is", "Are", "For", "In", "Of", "By", "To"}
    proper_nouns = [w for w in query_words if w not in stopwords]

    # Check if proper nouns appear in any result title or body
    result_text = " ".join(f"{r.get('title', '')} {r.get('body', '')}" for r in results)
    grounded = all(pn in result_text for pn in proper_nouns) if proper_nouns else True

    # Build context blocks with [Source N] labels
    context_blocks = []
    for i, result in enumerate(results, start=1):
        header = f"[Source {i}] WEB | {result['title']}\nURL: {result['href']}"
        body = result['body']
        context_blocks.append(f"{header}\n{body}")

    context_text = "\n\n---\n\n".join(context_blocks)

    user_content = f"Web search results:\n\n{context_text}\n\n---\n\nQuestion: {query}"
    if conversation_history:
        history_lines = []
        for turn in conversation_history:
            role = "User" if turn.get("role") == "user" else "Assistant"
            history_lines.append(f"{role}: {turn.get('content', '')}")
        history_text = "\n".join(history_lines)
        user_content = f"Prior conversation:\n{history_text}\n\n---\n\n{user_content}"

    try:
        response = ollama.chat(
            model=OLLAMA_MODEL,
            messages=[
                {"role": "system", "content": WEB_SYSTEM_PROMPT},
                {"role": "user", "content": user_content},
            ],
        )
    except Exception as e:
        if "connection" in str(e).lower():
            print("Ollama is not running. Start it with: ollama serve")
            return "", 0, 0, 0, True
        raise

    answer = response.message.content

    # Print for user visibility
    print(f"\n{answer}\n")
    print("---")
    print("Sources:")
    for i, result in enumerate(results, start=1):
        print(f"  [{i}] {result['title']}")
        print(f"      {result['href']}")

    tokens_in = getattr(response, 'prompt_eval_count', 0) or 0
    tokens_out = getattr(response, 'eval_count', 0) or 0

    return answer, len(results), tokens_in, tokens_out, grounded
